# Generated by Django 4.0.4 on 2023-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtrail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100)),
                ('title_desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
